spring.application.name=warehouse

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/warehouse}
spring.datasource.username=${DB_USER:warehouse}
spring.datasource.password=${DB_PASSWORD:warehouse}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.liquibase.change-log=classpath:db/changelog/master.xml